import { GoalItem } from '../../types/goalPlanning';

export const HACKATHON_DEMO_DATA = {
  monthlyIncome: 75000,
  essentialExpenses: 35000,
  activeEMI: 8000,
  recurringBills: 0,
  emergencyAllocation: 0,
  availableCapacity: 32000, // 75000 - 35000 - 8000 = 32000

  goals: [
    {
      id: 101,
      name: 'Family Dream Home Purchase',
      emoji: '🏡',
      category: 'Real Estate',
      targetAmount: 1000000,
      currentAmount: 200000,
      targetDate: 'Dec 2030',
      monthlyContribution: 18000,
      priority: 'HIGH' as const,
      priorityLabel: 'HIGH',
      hardDeadline: true,
      deadlineFlexibilityMonths: 0,
      minimumAcceptableAmount: 850000,
      expectedAnnualReturn: 8,
      inflationRate: 6,
      riskTolerance: 'MODERATE' as const,
      essentiality: 'MANDATORY' as const,
      canPause: false,
      canReduceTarget: true,
      isFamilyGoal: true,
      familyMemberOwner: 'Family Shared'
    },
    {
      id: 102,
      name: 'Ananya Higher Education Fund',
      emoji: '🎓',
      category: 'Education',
      targetAmount: 500000,
      currentAmount: 100000,
      targetDate: 'Aug 2029',
      monthlyContribution: 15000,
      priority: 'HIGH' as const,
      priorityLabel: 'HIGH',
      hardDeadline: true,
      deadlineFlexibilityMonths: 6,
      minimumAcceptableAmount: 400000,
      expectedAnnualReturn: 8,
      inflationRate: 7,
      riskTolerance: 'CONSERVATIVE' as const,
      essentiality: 'MANDATORY' as const,
      canPause: false,
      canReduceTarget: true,
      isFamilyGoal: true,
      familyMemberOwner: 'Ananya Sharma'
    },
    {
      id: 103,
      name: 'Emergency Shield Reserve',
      emoji: '🛡️',
      category: 'Emergency',
      targetAmount: 200000,
      currentAmount: 100000,
      targetDate: 'Dec 2027',
      monthlyContribution: 5000,
      priority: 'CRITICAL' as const,
      priorityLabel: 'CRITICAL',
      hardDeadline: true,
      deadlineFlexibilityMonths: 0,
      minimumAcceptableAmount: 200000,
      expectedAnnualReturn: 5,
      inflationRate: 5,
      riskTolerance: 'CONSERVATIVE' as const,
      essentiality: 'MANDATORY' as const,
      canPause: false,
      canReduceTarget: false,
      isFamilyGoal: true,
      familyMemberOwner: 'Priyanshu Sharma'
    },
    {
      id: 104,
      name: 'Long-Term Retirement Corpus',
      emoji: '🏖️',
      category: 'Retirement',
      targetAmount: 2000000,
      currentAmount: 300000,
      targetDate: 'Dec 2040',
      monthlyContribution: 10000,
      priority: 'MEDIUM' as const,
      priorityLabel: 'MEDIUM',
      hardDeadline: false,
      deadlineFlexibilityMonths: 24,
      minimumAcceptableAmount: 1500000,
      expectedAnnualReturn: 10,
      inflationRate: 6,
      riskTolerance: 'AGGRESSIVE' as const,
      essentiality: 'IMPORTANT' as const,
      canPause: true,
      canReduceTarget: true,
      isFamilyGoal: true,
      familyMemberOwner: 'Rajesh & Sunita'
    }
  ] as GoalItem[]
};
